#!/bin/bash

set -e
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --no-input

# uwsgi --socket :8000 --master --enable-threads --module app.wsgi
gunicorn notes_project.wsgi:application \
  --bind 0.0.0.0:8000 \
  --workers 4 \
  --timeout 120