services:
  noteapp:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: /start
    # command: sh -c "gunicorn notes_project.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOST=127.0.0.1, localhost
    depends_on:
      - postgres-db
    networks:
      - note-app-network

  postgres-db:
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - note-app-network
  ngnix:
    build:
      context: ./docker/ngnix
      dockerfile: Dockerfile

    restart: always
    depends_on:
      - noteapp
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - '80:80'
    networks:
      - note-app-network

networks:
  note-app-network:
    driver: bridge
    # external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:


