services:
  noteapp:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env
    # command: sh -c "gunicorn notes_project.wsgi:application --bind 0.0.0.0:8000"
    command: ./docker/django/scripts
    environment:
      - DEBUG=1
    depends_on:
      - postgres-db
    networks:
      - note-app-network

  postgres-db:
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - note-app-network

networks:
  note-app-network:
    driver: bridge
    # external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:


