#!bin/bash/

set -o errexit

set -o pipefail

set -o nounset

python3 manage.py makemigrations --no-input
python3 manage.py migrate --no-input

python3 manage.py collectstatic --no-input


# uwsgi --socket :8000 --master --enable-threads --module app.wsgi
gunicorn notes_project.wsgi:application \
  --bind 0.0.0.0:8000 \
  --workers 4 \
  --timeout 120
